version: '3.8'

services:
  server:
    container_name: cobrando-test
    restart: always
    build: .
    depends_on:
      - database
    ports:
      - "1234:3001"
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules

  
  database:
    container_name: postgredatabase
    image: postgres:14.5
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST = 127.0.0.1
      - POSTGRES_USER = root
      - POSTGRES_PASSWORD = root
      - POSTGRES_DB= root