version: '3.8'

services:
  server:
    container_name: cobrando-test
    restart: always
    build: 
      context: .

    depends_on:
      - database
    ports:
      - "1234:3001"
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules

  
  database:
    container_name: postgredatabase
    image: postgres:14.5
    restart: always
    ports:
      - "5432:5432"
    environment:
      ##DATABASE_HOST : postgres
      ##POSTGRES_USER : postgres
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
